# documentação sobre comunicação entre jobs
# https://docs.github.com/pt/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs


#para criar actions de forma rapida vale a pena conferir o toolkit https://github.com/actions/toolkit

name: comunicacao entre jobs
run-name: "comunicação entre runners executado por ${{ github.actor }} " 

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  CI:
    name: ci - job1
    runs-on: ubuntu-latest
    outputs:
      primeiro: ${{ steps.idStep1.outputs.primeriaSaida }}
      segundo: ${{ steps.saida.outputs.segundaSaida }}
    steps:
      - name: step1
        id: idStep1
        run: echo primeriaSaida=valor1 >> $GITHUB_OUTPUT
      - name: step2
        id: saida
        run: echo segundaSaida=valor2 >> $GITHUB_OUTPUT

       # documentação comandos extras no shell
       # https://docs.github.com/pt/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions?tool=bash
      - name: mascanrando variavel
        id: mascara
        run: | 
          valorprotegido="senhaRecebidoPorVault"
          echo "::add-mask::$valorprotegido"
          echo "::add-mask::bruno"
          echo $valorprotegido

          
      - name: lendo variavel segura
        run: echo "$PROTECAO"

  VERIFY:
    name: verifica job
    runs-on: ubuntu-latest
    needs: CI      
    env:
      primeiro: ${{ needs.CI.outputs.primeiro }}
      segundo: ${{ needs.CI.outputs.segundo }}
    steps:
      - run: echo "$primeiro"
      - run: echo "$segundo"
      - name: criando outra variavel de ambiente
        run: echo "NOVAVARIAVEL=novoValor" >> $GITHUB_ENV

      - name: acessando variavel criada
        run: echo $NOVAVARIAVEL
        

