name: primeiro-workflow #nome do workflow que sera exibido 
run-name: workflow executado por ${{ github.actor }} # contexto github.actor obtem o usuario que executou o workflow


# url com todos os tipos de gatilhos (triggers de workflows aceitaveis) 
#https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows

# confira a sintaxe aqui
#https://docs.github.com/pt/actions/writing-workflows/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows

on: 
  push:
    branches:
      - main
    paths:
      - '**.js'

  workflow_dispatch:
    inputs:
      nome-da-tecnologia:
        type: choice
        options:
          - Java
          - C#
          - GO
          - NODE
          - OUTRO
        required: true
        description: informe o nome da tecnologia
        default: OUTRO
      versao:
        required: true
        description: informe a versão
        default: '1.0'
    
      

jobs:
  teste-ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: primeiro step
        run: echo "lorem ipsum"  
  
      - name: exibindo inputs
        run: |
         echo "mostrando versao"
         echo ${{ inputs.versao }}
         echo ${{ inputs.nome-da-tecnologia }}
  

        # documentação de context 
        #https://docs.github.com/pt/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#example-contents-of-the-github-context
     
      - name: listando contexts
        run: |
         echo ${{ github.ref }} #obtem a branch
         echo ${{ github.repository }} #obtem o repositorio
         echo ${{ github.sha }} #obtem o hash do ultimo commit
         echo ${{ github.run_number }} #obtem o numero da execução do job
         echo ${{ github.event_name }} #nome do evento
         echo ${{ job.status }}
         echo ${{ github.event_name }}

      - name: trabalhando com summary
        run: |
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY

       # mais uma documentação
       # https://docs.github.com/pt/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions


        # documentação da action checkout https://github.com/actions/checkout
      - name: checkout (lendo repositorio)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # apontando para a brach na qual o workflow foi executado referencia


      - name: criando arquivo para cache
        run: echo ${{ github.run_number }} > resultado.txt

        # documentação de como trabalhar com artifact
        # https://github.com/marketplace/actions/upload-a-build-artifact
      - name: artifactory upload
        uses: actions/upload-artifact@v4.4.3
        with:
          name: arquivo #nome do artefato
          path: resultado.txt #diretorio ou arquivo 
          if-no-files-found: warn # defino para a pipe quebrar caso não encontre o arquivo no path 
          retention-days: 1 # limite de 1 a 90 dias 
          compression-level: 9 # nivel de compressão de 0 a 9 

      - name: artifactory download
        uses: actions/download-artifact@v4.1.8
        # with:
        #   path: /

      - run: ls -alh

      - name: cache
        uses: actions/cache@v4
        with:
          fail-on-cache-miss: true # defino a step para falhar caso não encontre o cache (util para etapa de recuperacao)
          # lookup-only: true
          key: ${{ runner.os }}-${{ hashFiles('**/*.yml') }} # chave usada para salvar e recuperar o cache
          path: resultado.txt

         # quando usar artifact vs cache ?
         # use artifact quando tu precisar deixar um resultado disponivel para donwload no final
         # cache utilize para processos e circuitos internos na esteira

         # entre cache e artifact todos eles usam o mesmo espaço por repositorio de 10GB
         # quando essa quantia é atingida o github analisa os ultimos cache acessados e começa a apagar para
         # liberar espaço
          
          

        

             
