name: primeiro-workflow #nome do workflow que sera exibido 
run-name: workflow executado por ${{ github.actor }}


# url com todos os tipos de gatilhos (triggers de workflows aceitaveis) 
#https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
# confira a sintaxe aqui
#https://docs.github.com/pt/actions/writing-workflows/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows


on: 
  workflow_dispatch:
    inputs:
      nome-da-tecnologia:
        type: choice
        options:
          - Java
          - C#
          - GO
          - NODE
          - OUTRO
        required: true
        description: informe o nome da tecnologia
        default: OUTRO
      versao:
        type: text
        required: true
        description: informe a versão
        default: '1.0'
      

jobs:
  teste-ci:
   name: ci
   runs-on: ubuntu-latest
   steps:
     - name: primeiro step
       run: echo "lorem ipsum"  

     - name: listando inputs
       run: |
         echo ${{ inputs.nome-da-tecnologia }}
         echo ${{ inputs.versao }}

      
