name: teste token

on: 
  workflow_dispatch:
    inputs:
      brntoken:
        description: 'Token'
        required: true
        type: string      

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ inputs.brntoken }}

