name: teste token

on: [workflow_dispatch]

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: teste
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.tokenbrn }}
